# Generated by Django 4.1.7 on 2023-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlert', '0002_fcmtoken_delete_fcm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='tokens',
            field=models.JSONField(default=list),
        ),
    ]
