# Generated by Django 4.1.9 on 2023-08-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAlert', '0004_usertokens_delete_fcmtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTokens',
            new_name='ConcreteUserTokens',
        ),
    ]
