# Generated by Django 4.1.9 on 2023-08-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAlert', '0005_rename_usertokens_concreteusertokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcreteUserTokens',
            new_name='FCMUserTokens',
        ),
    ]
